// Note: Protobuf Edition 2023 is the latest available. Edition 2026 does not exist yet.
// For compatibility with the current @bufbuild tools, proto3 is the standard syntax used.

// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file types.proto (package mkw.shared, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum mkw.shared.Confidence
 */
export enum Confidence {
  /**
   * CSV empty + No guess. UI: User must select.
   *
   * @generated from enum value: CONFIDENCE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * CSV empty + Heuristic guess. UI: User must confirm.
   *
   * @generated from enum value: CONFIDENCE_UNCERTAIN = 1;
   */
  UNCERTAIN = 1,

  /**
   * Value in CSV. UI: Pre-filled, user can skip.
   *
   * @generated from enum value: CONFIDENCE_CERTAIN = 2;
   */
  CERTAIN = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(Confidence)
proto3.util.setEnumType(Confidence, "mkw.shared.Confidence", [
  { no: 0, name: "CONFIDENCE_UNKNOWN" },
  { no: 1, name: "CONFIDENCE_UNCERTAIN" },
  { no: 2, name: "CONFIDENCE_CERTAIN" },
]);

/**
 * @generated from enum mkw.shared.RacePhase
 */
export enum RacePhase {
  /**
   * @generated from enum value: PHASE_UNKNOWN = 0;
   */
  PHASE_UNKNOWN = 0,

  /**
   * @generated from enum value: PHASE_LOADING = 1;
   */
  PHASE_LOADING = 1,

  /**
   * @generated from enum value: PHASE_COUNTDOWN = 2;
   */
  PHASE_COUNTDOWN = 2,

  /**
   * @generated from enum value: PHASE_RACING = 3;
   */
  PHASE_RACING = 3,

  /**
   * @generated from enum value: PHASE_PAUSED = 4;
   */
  PHASE_PAUSED = 4,

  /**
   * @generated from enum value: PHASE_FINISHED = 5;
   */
  PHASE_FINISHED = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(RacePhase)
proto3.util.setEnumType(RacePhase, "mkw.shared.RacePhase", [
  { no: 0, name: "PHASE_UNKNOWN" },
  { no: 1, name: "PHASE_LOADING" },
  { no: 2, name: "PHASE_COUNTDOWN" },
  { no: 3, name: "PHASE_RACING" },
  { no: 4, name: "PHASE_PAUSED" },
  { no: 5, name: "PHASE_FINISHED" },
]);

/**
 * @generated from enum mkw.shared.ItemType
 */
export enum ItemType {
  /**
   * @generated from enum value: ITEM_NONE = 0;
   */
  ITEM_NONE = 0,

  /**
   * @generated from enum value: ITEM_COIN = 1;
   */
  ITEM_COIN = 1,

  /**
   * @generated from enum value: ITEM_MUSHROOM = 2;
   */
  ITEM_MUSHROOM = 2,

  /**
   * @generated from enum value: ITEM_TRIPLE_MUSHROOM = 3;
   */
  ITEM_TRIPLE_MUSHROOM = 3,

  /**
   * @generated from enum value: ITEM_GOLDEN_MUSHROOM = 4;
   */
  ITEM_GOLDEN_MUSHROOM = 4,

  /**
   * @generated from enum value: ITEM_GREEN_SHELL = 5;
   */
  ITEM_GREEN_SHELL = 5,

  /**
   * @generated from enum value: ITEM_TRIPLE_GREEN_SHELLS = 6;
   */
  ITEM_TRIPLE_GREEN_SHELLS = 6,

  /**
   * @generated from enum value: ITEM_RED_SHELL = 7;
   */
  ITEM_RED_SHELL = 7,

  /**
   * @generated from enum value: ITEM_TRIPLE_RED_SHELLS = 8;
   */
  ITEM_TRIPLE_RED_SHELLS = 8,

  /**
   * @generated from enum value: ITEM_BANANA = 9;
   */
  ITEM_BANANA = 9,

  /**
   * @generated from enum value: ITEM_TRIPLE_BANANAS = 10;
   */
  ITEM_TRIPLE_BANANAS = 10,

  /**
   * @generated from enum value: ITEM_BOB_OMB = 11;
   */
  ITEM_BOB_OMB = 11,

  /**
   * @generated from enum value: ITEM_STAR = 12;
   */
  ITEM_STAR = 12,

  /**
   * @generated from enum value: ITEM_LIGHTNING = 13;
   */
  ITEM_LIGHTNING = 13,

  /**
   * @generated from enum value: ITEM_BULLET_BILL = 14;
   */
  ITEM_BULLET_BILL = 14,

  /**
   * @generated from enum value: ITEM_BLOOPER = 15;
   */
  ITEM_BLOOPER = 15,

  /**
   * @generated from enum value: ITEM_BOO = 16;
   */
  ITEM_BOO = 16,

  /**
   * @generated from enum value: ITEM_BOOMERANG = 18;
   */
  ITEM_BOOMERANG = 18,

  /**
   * @generated from enum value: ITEM_SUPER_HORN = 19;
   */
  ITEM_SUPER_HORN = 19,

  /**
   * Spinning state
   *
   * @generated from enum value: ITEM_ROULETTE = 21;
   */
  ITEM_ROULETTE = 21,

  /**
   * Mario Kart World Exclusive/New Items
   *
   * @generated from enum value: ITEM_COIN_SHELL = 22;
   */
  ITEM_COIN_SHELL = 22,

  /**
   * @generated from enum value: ITEM_DASH_FOOD = 23;
   */
  ITEM_DASH_FOOD = 23,

  /**
   * @generated from enum value: ITEM_KAMEK = 24;
   */
  ITEM_KAMEK = 24,

  /**
   * Blue shell
   *
   * @generated from enum value: ITEM_SPINY_SHELL = 25;
   */
  ITEM_SPINY_SHELL = 25,

  /**
   * @generated from enum value: ITEM_FIRE_FLOWER = 26;
   */
  ITEM_FIRE_FLOWER = 26,

  /**
   * @generated from enum value: ITEM_ICE_FLOWER = 27;
   */
  ITEM_ICE_FLOWER = 27,

  /**
   * @generated from enum value: ITEM_HAMMER = 28;
   */
  ITEM_HAMMER = 28,

  /**
   * @generated from enum value: ITEM_FEATHER = 29;
   */
  ITEM_FEATHER = 29,

  /**
   * @generated from enum value: ITEM_COIN_BOX = 30;
   */
  ITEM_COIN_BOX = 30,

  /**
   * @generated from enum value: ITEM_UNKNOWN = 31;
   */
  ITEM_UNKNOWN = 31,
}
// Retrieve enum metadata with: proto3.getEnumType(ItemType)
proto3.util.setEnumType(ItemType, "mkw.shared.ItemType", [
  { no: 0, name: "ITEM_NONE" },
  { no: 1, name: "ITEM_COIN" },
  { no: 2, name: "ITEM_MUSHROOM" },
  { no: 3, name: "ITEM_TRIPLE_MUSHROOM" },
  { no: 4, name: "ITEM_GOLDEN_MUSHROOM" },
  { no: 5, name: "ITEM_GREEN_SHELL" },
  { no: 6, name: "ITEM_TRIPLE_GREEN_SHELLS" },
  { no: 7, name: "ITEM_RED_SHELL" },
  { no: 8, name: "ITEM_TRIPLE_RED_SHELLS" },
  { no: 9, name: "ITEM_BANANA" },
  { no: 10, name: "ITEM_TRIPLE_BANANAS" },
  { no: 11, name: "ITEM_BOB_OMB" },
  { no: 12, name: "ITEM_STAR" },
  { no: 13, name: "ITEM_LIGHTNING" },
  { no: 14, name: "ITEM_BULLET_BILL" },
  { no: 15, name: "ITEM_BLOOPER" },
  { no: 16, name: "ITEM_BOO" },
  { no: 18, name: "ITEM_BOOMERANG" },
  { no: 19, name: "ITEM_SUPER_HORN" },
  { no: 21, name: "ITEM_ROULETTE" },
  { no: 22, name: "ITEM_COIN_SHELL" },
  { no: 23, name: "ITEM_DASH_FOOD" },
  { no: 24, name: "ITEM_KAMEK" },
  { no: 25, name: "ITEM_SPINY_SHELL" },
  { no: 26, name: "ITEM_FIRE_FLOWER" },
  { no: 27, name: "ITEM_ICE_FLOWER" },
  { no: 28, name: "ITEM_HAMMER" },
  { no: 29, name: "ITEM_FEATHER" },
  { no: 30, name: "ITEM_COIN_BOX" },
  { no: 31, name: "ITEM_UNKNOWN" },
]);

/**
 * @generated from enum mkw.shared.Placement
 */
export enum Placement {
  /**
   * @generated from enum value: PLACE_UNKNOWN = 0;
   */
  PLACE_UNKNOWN = 0,

  /**
   * @generated from enum value: PLACE_1 = 1;
   */
  PLACE_1 = 1,

  /**
   * @generated from enum value: PLACE_2 = 2;
   */
  PLACE_2 = 2,

  /**
   * @generated from enum value: PLACE_3 = 3;
   */
  PLACE_3 = 3,

  /**
   * @generated from enum value: PLACE_4 = 4;
   */
  PLACE_4 = 4,

  /**
   * @generated from enum value: PLACE_5 = 5;
   */
  PLACE_5 = 5,

  /**
   * @generated from enum value: PLACE_6 = 6;
   */
  PLACE_6 = 6,

  /**
   * @generated from enum value: PLACE_7 = 7;
   */
  PLACE_7 = 7,

  /**
   * @generated from enum value: PLACE_8 = 8;
   */
  PLACE_8 = 8,

  /**
   * @generated from enum value: PLACE_9 = 9;
   */
  PLACE_9 = 9,

  /**
   * @generated from enum value: PLACE_10 = 10;
   */
  PLACE_10 = 10,

  /**
   * @generated from enum value: PLACE_11 = 11;
   */
  PLACE_11 = 11,

  /**
   * @generated from enum value: PLACE_12 = 12;
   */
  PLACE_12 = 12,

  /**
   * @generated from enum value: PLACE_13 = 13;
   */
  PLACE_13 = 13,

  /**
   * @generated from enum value: PLACE_14 = 14;
   */
  PLACE_14 = 14,

  /**
   * @generated from enum value: PLACE_15 = 15;
   */
  PLACE_15 = 15,

  /**
   * @generated from enum value: PLACE_16 = 16;
   */
  PLACE_16 = 16,

  /**
   * @generated from enum value: PLACE_17 = 17;
   */
  PLACE_17 = 17,

  /**
   * @generated from enum value: PLACE_18 = 18;
   */
  PLACE_18 = 18,

  /**
   * @generated from enum value: PLACE_19 = 19;
   */
  PLACE_19 = 19,

  /**
   * @generated from enum value: PLACE_20 = 20;
   */
  PLACE_20 = 20,

  /**
   * @generated from enum value: PLACE_21 = 21;
   */
  PLACE_21 = 21,

  /**
   * @generated from enum value: PLACE_22 = 22;
   */
  PLACE_22 = 22,

  /**
   * @generated from enum value: PLACE_23 = 23;
   */
  PLACE_23 = 23,

  /**
   * @generated from enum value: PLACE_24 = 24;
   */
  PLACE_24 = 24,
}
// Retrieve enum metadata with: proto3.getEnumType(Placement)
proto3.util.setEnumType(Placement, "mkw.shared.Placement", [
  { no: 0, name: "PLACE_UNKNOWN" },
  { no: 1, name: "PLACE_1" },
  { no: 2, name: "PLACE_2" },
  { no: 3, name: "PLACE_3" },
  { no: 4, name: "PLACE_4" },
  { no: 5, name: "PLACE_5" },
  { no: 6, name: "PLACE_6" },
  { no: 7, name: "PLACE_7" },
  { no: 8, name: "PLACE_8" },
  { no: 9, name: "PLACE_9" },
  { no: 10, name: "PLACE_10" },
  { no: 11, name: "PLACE_11" },
  { no: 12, name: "PLACE_12" },
  { no: 13, name: "PLACE_13" },
  { no: 14, name: "PLACE_14" },
  { no: 15, name: "PLACE_15" },
  { no: 16, name: "PLACE_16" },
  { no: 17, name: "PLACE_17" },
  { no: 18, name: "PLACE_18" },
  { no: 19, name: "PLACE_19" },
  { no: 20, name: "PLACE_20" },
  { no: 21, name: "PLACE_21" },
  { no: 22, name: "PLACE_22" },
  { no: 23, name: "PLACE_23" },
  { no: 24, name: "PLACE_24" },
]);

/**
 * @generated from enum mkw.shared.LapCount
 */
export enum LapCount {
  /**
   * @generated from enum value: LAP_UNKNOWN = 0;
   */
  LAP_UNKNOWN = 0,

  /**
   * @generated from enum value: LAP_1 = 1;
   */
  LAP_1 = 1,

  /**
   * @generated from enum value: LAP_2 = 2;
   */
  LAP_2 = 2,

  /**
   * @generated from enum value: LAP_3 = 3;
   */
  LAP_3 = 3,

  /**
   * @generated from enum value: LAP_4 = 4;
   */
  LAP_4 = 4,

  /**
   * @generated from enum value: LAP_5 = 5;
   */
  LAP_5 = 5,

  /**
   * @generated from enum value: LAP_6 = 6;
   */
  LAP_6 = 6,

  /**
   * @generated from enum value: LAP_7 = 7;
   */
  LAP_7 = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(LapCount)
proto3.util.setEnumType(LapCount, "mkw.shared.LapCount", [
  { no: 0, name: "LAP_UNKNOWN" },
  { no: 1, name: "LAP_1" },
  { no: 2, name: "LAP_2" },
  { no: 3, name: "LAP_3" },
  { no: 4, name: "LAP_4" },
  { no: 5, name: "LAP_5" },
  { no: 6, name: "LAP_6" },
  { no: 7, name: "LAP_7" },
]);

/**
 * @generated from enum mkw.shared.Track
 */
export enum Track {
  /**
   * @generated from enum value: TRACK_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: TRACK_RAINBOW_ROAD = 1;
   */
  RAINBOW_ROAD = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(Track)
proto3.util.setEnumType(Track, "mkw.shared.Track", [
  { no: 0, name: "TRACK_UNKNOWN" },
  { no: 1, name: "TRACK_RAINBOW_ROAD" },
]);

/**
 * @generated from message mkw.shared.RaceMetadata
 */
export class RaceMetadata extends Message<RaceMetadata> {
  /**
   * @generated from field: mkw.shared.Track track = 1;
   */
  track = Track.UNKNOWN;

  /**
   * @generated from field: int32 total_laps = 2;
   */
  totalLaps = 0;

  constructor(data?: PartialMessage<RaceMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "mkw.shared.RaceMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "track", kind: "enum", T: proto3.getEnumType(Track) },
    { no: 2, name: "total_laps", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RaceMetadata {
    return new RaceMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RaceMetadata {
    return new RaceMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RaceMetadata {
    return new RaceMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: RaceMetadata | PlainMessage<RaceMetadata> | undefined, b: RaceMetadata | PlainMessage<RaceMetadata> | undefined): boolean {
    return proto3.util.equals(RaceMetadata, a, b);
  }
}

/**
 * Defines a Backend Heuristic Guess
 *
 * @generated from message mkw.shared.TelemetryGuess
 */
export class TelemetryGuess extends Message<TelemetryGuess> {
  /**
   * @generated from field: mkw.shared.Confidence confidence = 1;
   */
  confidence = Confidence.UNKNOWN;

  /**
   * @generated from oneof mkw.shared.TelemetryGuess.value
   */
  value: {
    /**
     * @generated from field: mkw.shared.Placement placement = 2;
     */
    value: Placement;
    case: "placement";
  } | {
    /**
     * @generated from field: mkw.shared.LapCount lap_count = 3;
     */
    value: LapCount;
    case: "lapCount";
  } | {
    /**
     * @generated from field: int32 coin_count = 4;
     */
    value: number;
    case: "coinCount";
  } | {
    /**
     * @generated from field: mkw.shared.ItemType item = 5;
     */
    value: ItemType;
    case: "item";
  } | {
    /**
     * @generated from field: mkw.shared.RacePhase race_phase = 6;
     */
    value: RacePhase;
    case: "racePhase";
  } | {
    /**
     * @generated from field: mkw.shared.Track track = 7;
     */
    value: Track;
    case: "track";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<TelemetryGuess>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "mkw.shared.TelemetryGuess";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "confidence", kind: "enum", T: proto3.getEnumType(Confidence) },
    { no: 2, name: "placement", kind: "enum", T: proto3.getEnumType(Placement), oneof: "value" },
    { no: 3, name: "lap_count", kind: "enum", T: proto3.getEnumType(LapCount), oneof: "value" },
    { no: 4, name: "coin_count", kind: "scalar", T: 5 /* ScalarType.INT32 */, oneof: "value" },
    { no: 5, name: "item", kind: "enum", T: proto3.getEnumType(ItemType), oneof: "value" },
    { no: 6, name: "race_phase", kind: "enum", T: proto3.getEnumType(RacePhase), oneof: "value" },
    { no: 7, name: "track", kind: "enum", T: proto3.getEnumType(Track), oneof: "value" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TelemetryGuess {
    return new TelemetryGuess().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TelemetryGuess {
    return new TelemetryGuess().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TelemetryGuess {
    return new TelemetryGuess().fromJsonString(jsonString, options);
  }

  static equals(a: TelemetryGuess | PlainMessage<TelemetryGuess> | undefined, b: TelemetryGuess | PlainMessage<TelemetryGuess> | undefined): boolean {
    return proto3.util.equals(TelemetryGuess, a, b);
  }
}

/**
 * 1. Requesting a frame and its info to classify (Backend decides what to serve next)
 *
 * @generated from message mkw.shared.GetFrameClassificationRequest
 */
export class GetFrameClassificationRequest extends Message<GetFrameClassificationRequest> {
  constructor(data?: PartialMessage<GetFrameClassificationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "mkw.shared.GetFrameClassificationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetFrameClassificationRequest {
    return new GetFrameClassificationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetFrameClassificationRequest {
    return new GetFrameClassificationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetFrameClassificationRequest {
    return new GetFrameClassificationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetFrameClassificationRequest | PlainMessage<GetFrameClassificationRequest> | undefined, b: GetFrameClassificationRequest | PlainMessage<GetFrameClassificationRequest> | undefined): boolean {
    return proto3.util.equals(GetFrameClassificationRequest, a, b);
  }
}

/**
 * 1. Getting the frame and info back
 *
 * @generated from message mkw.shared.GetFrameClassificationResponse
 */
export class GetFrameClassificationResponse extends Message<GetFrameClassificationResponse> {
  /**
   * @generated from field: string frame_id = 1;
   */
  frameId = "";

  /**
   * @generated from field: string image_url = 2;
   */
  imageUrl = "";

  /**
   * @generated from field: mkw.shared.RaceMetadata metadata = 3;
   */
  metadata?: RaceMetadata;

  /**
   * @generated from field: mkw.shared.TelemetryGuess placement = 4;
   */
  placement?: TelemetryGuess;

  /**
   * @generated from field: mkw.shared.TelemetryGuess lap_count = 5;
   */
  lapCount?: TelemetryGuess;

  /**
   * @generated from field: mkw.shared.TelemetryGuess coin_count = 6;
   */
  coinCount?: TelemetryGuess;

  /**
   * @generated from field: mkw.shared.TelemetryGuess primary_item = 7;
   */
  primaryItem?: TelemetryGuess;

  /**
   * @generated from field: mkw.shared.TelemetryGuess secondary_item = 8;
   */
  secondaryItem?: TelemetryGuess;

  /**
   * @generated from field: mkw.shared.TelemetryGuess race_phase = 9;
   */
  racePhase?: TelemetryGuess;

  constructor(data?: PartialMessage<GetFrameClassificationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "mkw.shared.GetFrameClassificationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "frame_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "metadata", kind: "message", T: RaceMetadata },
    { no: 4, name: "placement", kind: "message", T: TelemetryGuess },
    { no: 5, name: "lap_count", kind: "message", T: TelemetryGuess },
    { no: 6, name: "coin_count", kind: "message", T: TelemetryGuess },
    { no: 7, name: "primary_item", kind: "message", T: TelemetryGuess },
    { no: 8, name: "secondary_item", kind: "message", T: TelemetryGuess },
    { no: 9, name: "race_phase", kind: "message", T: TelemetryGuess },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetFrameClassificationResponse {
    return new GetFrameClassificationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetFrameClassificationResponse {
    return new GetFrameClassificationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetFrameClassificationResponse {
    return new GetFrameClassificationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetFrameClassificationResponse | PlainMessage<GetFrameClassificationResponse> | undefined, b: GetFrameClassificationResponse | PlainMessage<GetFrameClassificationResponse> | undefined): boolean {
    return proto3.util.equals(GetFrameClassificationResponse, a, b);
  }
}

/**
 * 2. Sending the guesses back
 *
 * @generated from message mkw.shared.SaveFrameClassificationRequest
 */
export class SaveFrameClassificationRequest extends Message<SaveFrameClassificationRequest> {
  /**
   * @generated from field: string frame_id = 1;
   */
  frameId = "";

  /**
   * @generated from field: mkw.shared.Placement placement = 2;
   */
  placement = Placement.PLACE_UNKNOWN;

  /**
   * @generated from field: mkw.shared.LapCount lap_count = 3;
   */
  lapCount = LapCount.LAP_UNKNOWN;

  /**
   * @generated from field: optional int32 coin_count = 4;
   */
  coinCount?: number;

  /**
   * @generated from field: mkw.shared.ItemType primary_item = 5;
   */
  primaryItem = ItemType.ITEM_NONE;

  /**
   * @generated from field: mkw.shared.ItemType secondary_item = 6;
   */
  secondaryItem = ItemType.ITEM_NONE;

  /**
   * @generated from field: mkw.shared.RacePhase race_phase = 7;
   */
  racePhase = RacePhase.PHASE_UNKNOWN;

  /**
   * @generated from field: mkw.shared.Track track = 8;
   */
  track = Track.UNKNOWN;

  constructor(data?: PartialMessage<SaveFrameClassificationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "mkw.shared.SaveFrameClassificationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "frame_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "placement", kind: "enum", T: proto3.getEnumType(Placement) },
    { no: 3, name: "lap_count", kind: "enum", T: proto3.getEnumType(LapCount) },
    { no: 4, name: "coin_count", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 5, name: "primary_item", kind: "enum", T: proto3.getEnumType(ItemType) },
    { no: 6, name: "secondary_item", kind: "enum", T: proto3.getEnumType(ItemType) },
    { no: 7, name: "race_phase", kind: "enum", T: proto3.getEnumType(RacePhase) },
    { no: 8, name: "track", kind: "enum", T: proto3.getEnumType(Track) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SaveFrameClassificationRequest {
    return new SaveFrameClassificationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SaveFrameClassificationRequest {
    return new SaveFrameClassificationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SaveFrameClassificationRequest {
    return new SaveFrameClassificationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SaveFrameClassificationRequest | PlainMessage<SaveFrameClassificationRequest> | undefined, b: SaveFrameClassificationRequest | PlainMessage<SaveFrameClassificationRequest> | undefined): boolean {
    return proto3.util.equals(SaveFrameClassificationRequest, a, b);
  }
}

/**
 * 2. Getting an okay back
 *
 * @generated from message mkw.shared.SaveFrameClassificationResponse
 */
export class SaveFrameClassificationResponse extends Message<SaveFrameClassificationResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<SaveFrameClassificationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "mkw.shared.SaveFrameClassificationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SaveFrameClassificationResponse {
    return new SaveFrameClassificationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SaveFrameClassificationResponse {
    return new SaveFrameClassificationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SaveFrameClassificationResponse {
    return new SaveFrameClassificationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SaveFrameClassificationResponse | PlainMessage<SaveFrameClassificationResponse> | undefined, b: SaveFrameClassificationResponse | PlainMessage<SaveFrameClassificationResponse> | undefined): boolean {
    return proto3.util.equals(SaveFrameClassificationResponse, a, b);
  }
}

